### ISSUE TITLE
Still having issues with configuration.yaml

### ISSUE THREAD

**Issue by SergeWSU** [mpi-astronomy/gdr3apcal#10]
New to python - so keep it simple if possible
PIP downloaded the utility and installed (Windows 10) got confirmation of successful build

Created a test result-1.csv (stored in D drive)

Quick run as follows:
>>> df = pandas.read_csv("d:result-1.csv")
>>> calib = gdr3apcal.GaiaDR3_GSPPhot_cal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\calibration.py", line 115, in __init__
    self._configuration = _read_configuration(configuration_file)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\calibration.py", line 18, in _read_configuration
    with open(fname, 'r') as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/configuration.yaml'

configuration.yaml is in the gdr3apcal folder so I don't know where I am going wrong.

Another student is running it successfully on a Mac

Regards
Serge

**Comment by SergeWSU** [comment]
Forgot to mention I did import

import gdr3apcal
import numpy
import pandas

**Comment by mfouesneau** [comment]
which version do you have installed?

```python
import gdr3apcal
print(""" 
Code version {0}
Package installed in: {1}
Model directory: {2}
""".format(gdr3apcal.__VERSION__, 
           gdr3apcal.config.__PACKAGE_DIR__, 
           gdr3apcal.config.modelsdir))
```

**Comment by mfouesneau** [comment]
Our CI tests do not show issues. Could it be that you have an older version of the package?

**Comment by SergeWSU** [comment]
Hi
Code version 1.6
Package installed in:
Model directory: C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\models

Regards
S

**Comment by mfouesneau** [comment]
[ee0a04e](https://github.com/mpi-astronomy/gdr3apcal/commit/ee0a04e8b022a803b4f9cb2688b18cd546923fb1)

Could you install this branch and try again?

pip install git+https://github.com/mpi-astronomy/gdr3apcal@10-still-having-issues-with-configurationyaml  --upgrade --force

**Comment by SergeWSU** [comment]
> [ee0a04e](https://github.com/mpi-astronomy/gdr3apcal/commit/ee0a04e8b022a803b4f9cb2688b18cd546923fb1)
> 
> Could you install this branch and try again?
> 
> pip install git+https://github.com/mpi-astronomy/gdr3apcal@10-still-having-issues-with-configurationyaml --upgrade --force

Hi
Get numerous errors when trying to upgrade from invalid distribution -yerfa to OS permission errors

Anyway to delete and start again with updated version?

S

**Comment by SergeWSU** [comment]
OK - I uninstalled the whole package and tried reinstalling

pip install git+https://github.com/mpi-astronomy/gdr3apcal@10-still-having-issues-with-configurationyaml

Got a successful install but with the warning

WARNING: Ignoring invalid distribution -yerfa (c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages)

No change in performance or version output.

S

**Comment by mfouesneau** [comment]
The warning does not matter.  
I cannot reproduce the issue. Can you provide the new error message?

**Comment by mfouesneau** [comment]
It seems I managed to get some tests running. However I am not sure it fixes your issue.

Note to self: Windows python (not Linux env) does not compute checksum in hashlib in the same way as linux env. I had to skip the test.

**Comment by mfouesneau** [comment]
Please try again with installing from the same branch (uninstall and reinstall)

**Comment by SergeWSU** [comment]
Done with no change.
No errors only warning as previously on reinstall.

 df = pandas.read_csv("d:result-1.csv")
>>> calib = gdr3apcal.GaiaDR3_GSPPhot_cal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\calibration.py", line 115, in __init__
    """ constructor """
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\calibration.py", line 18, in _read_configuration
    with open(fname, 'r', encoding='utf8') as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/configuration.yaml'


S

**Comment by mfouesneau** [comment]
It seems you do not get the warning I put in when reading the model. Are you positive you installed the branch?

**Comment by SergeWSU** [comment]
Some progress
I did a complete shutdown of the system after deleting.
Reboot and reinstalled from the branch above.

I can get past the configuration.yami block but now I get (See Below)

My CSV file is 
5957,4.16,-0.1438,0.0042,0.0019,0.0035,3.5485,"327.64, -27.81",MARCS

S
>>> metal_calib = calib.calibrateMetallicity(df)
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\models\mars_mh.py: 682ec200c6392244c50e5659a9ff9923f6dd1f801e33fabb40a9fa93ba58c031
Model mh (C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\models\mars_mh.py) input file does not match the configuration.Expecting bd102a2b38e161e6c770650e021d2d8696542e2bddd411d0a590fe28f24030fa, got 682ec200c6392244c50e5659a9ff9923f6dd1f801e33fabb40a9fa93ba58c031
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\calibration.py", line 133, in calibrateMetallicity
    return self['mh'](pandas_data_frame)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\calibration_models.py", line 178, in __call__
    for name, data in df.groupby(self.groupby):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\frame.py", line 7641, in groupby
    dropna=dropna,
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\groupby\groupby.py", line 897, in __init__
    dropna=self.dropna,
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\groupby\grouper.py", line 862, in get_grouper
    raise KeyError(gpr)
KeyError: 'libname_gspphot'

**Comment by mfouesneau** [comment]
Your CSV file may not have a column named `libname_gspphot`?

Since this is a different issue, I'll merge the branch
